/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "libopus/include/opus.h"

/*
 * Class:     com_cyf_opuscodec_OpusUtil
 * Method:    _createDecoder
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_cyf_opuscodec_OpusUtil_createDecoder
        (JNIEnv *env, jobject thiz, jint sampleRateInHz, jint channelConfig) {
    int error;
    OpusDecoder *pOpusDec = opus_decoder_create(sampleRateInHz, channelConfig, &error);
    return (jlong)
            pOpusDec;
}

/*
 * Class:     com_cyf_opuscodec_OpusUtil
 * Method:    _decode
 * Signature: (J[B[S)I
 */
JNIEXPORT jint JNICALL Java_com_cyf_opuscodec_OpusUtil_decode
        (JNIEnv *env, jobject thiz, jlong pOpusDec, jbyteArray bytes, jshortArray samples) {
    OpusDecoder *pDec = (OpusDecoder *) pOpusDec;
    if (!pDec || !samples || !bytes)
        return 0;
    jshort *pSamples = (*env)->GetShortArrayElements(env, samples, 0);
    jbyte *pBytes = (*env)->GetByteArrayElements(env, bytes, 0);
    jsize nByteSize = (*env)->GetArrayLength(env, bytes);
    jsize nShortSize = (*env)->GetArrayLength(env, samples);
    if (nByteSize <= 0 || nShortSize <= 0) {
        return -1;
    }
    int nRet = opus_decode(pDec, (unsigned char *) pBytes, nByteSize, pSamples, nShortSize, 0);
    (*env)->ReleaseShortArrayElements(env, samples, pSamples, 0);
    (*env)->ReleaseByteArrayElements(env, bytes, pBytes, 0);
    return nRet;
}

/*
 * Class:     com_cyf_opuscodec_OpusUtil
 * Method:    _destroyDecoder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_cyf_opuscodec_OpusUtil_destroyDecoder
        (JNIEnv *env, jobject thiz, jlong pOpusDec) {
    OpusDecoder *pDec = (OpusDecoder *) pOpusDec;
    if (!pDec)
        return;
    opus_decoder_destroy(pDec);
}

